server.error.include-message: always

app:
    eureka-server: localhost
    eureka-username: ${EUREKA_SERVER_USR}
    eureka-password: ${EUREKA_SERVER_PWD}

eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
    client:
        service-url.defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5

logging:
    level:
        root: info
        com.elys.pos: debug

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: dev

app.eureka-server: eureka