server.error.include-message: always
server.forward-headers-strategy: framework

app:
    eureka-server: ${EUREKA_SERVER}
    eureka-username: ${EUREKA_SERVER_USR}
    eureka-password: ${EUREKA_SERVER_PWD}
    auth-server-base: ${AUTH_SERVER_BASE}
    auth-server-realm: ${AUTH_SERVER_REALM}

eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
    client:
        service-url.defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}/eureka/
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5

logging:
    level:
        root: info
        com.elys.pos: debug

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: dev
