server.port: 8086

spring:
    security.oauth2.resourceserver.jwt:
        issuer-uri: http://${app.auth-server-base}/realms/${app.auth-server-realm}
        jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

logging:
    level:
        org.springframework.cloud.gateway: trace
        org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

spring.cloud.gateway.routes:
    - id: inventory
      uri: lb://inventory
      predicates:
          - Path=/v1/inventory/**
      filters:
          - RewritePath=/v1/inventory/(?<segment>.*), /v1/${segment}

    - id: eureka-api
      uri: http://${app.eureka-server}
      predicates:
          - Path=/eureka/api/{segment}
      filters:
          - SetPath=/eureka/{segment}

    - id: eureka-web
      uri: http://${app.eureka-server}
      predicates:
          - Path=/eureka/web
      filters:
          - SetPath=/

    - id: eureka-web-other
      uri: http://${app.eureka-server}
      predicates:
          - Path=/eureka/**

    - id: config-server
      uri: ${spring.cloud.config.uri}
      predicates:
          - Path=/config/**
      filters:
          - RewritePath=/config/(?<segment>.*), /$\{segment}

    - id: auth-server-discovery
      uri: http://${app.auth-server-base}
      predicates:
          - Path=/oauth2/.well-known/openid-configuration
      filters:
          - SetPath=/realms/${app.auth-server-realm}/.well-known/openid-configuration

    - id: auth-server-token
      uri: http://${app.auth-server-base}
      predicates:
          - Path=/oauth2/token
      filters:
          - SetPath=/realms/${app.auth-server-realm}/protocol/openid-connect/token

---
spring.config.activate.on-profile: dev

server.port: 8080