spring.application.name: inventory
server.port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory
    username: postgres
    password: password1234
    hikari.initialization-fail-timeout: 60000
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: false

logging:
  level:
    com.elys.pos: debug
    root: info
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE