spring.application.name: inventory

server.port: 8085

app:
    eureka-username: user
    eureka-password: pwd

spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/inventory
        username: postgres
        password: password1234
        hikari.initialization-fail-timeout: 60000
    jpa:
        hibernate.ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate.format_sql: false

eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        hostname: localhost
    client:
        service-url:
            defaultZone: http://${app.eureka-username}:${app.eureka-password}@${eureka.instance.hostname}:8761/eureka/
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5

logging:
    level:
        com.elys.pos: debug
        root: info

management.endpoints.web.exposure.include: "*"