services:
    postgres:
        image: postgres:14
        container_name: postgres
        mem_limit: 512m
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password1234
            - POSTGRES_DB=inventory
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 5s
            timeout: 2s
            retries: 60

    config-server:
        build: spring-cloud/config-server
        image: rufusy/elys-pos-config-server
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=dev,native
            - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
            - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
            - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
        volumes:
            -   $PWD/config-repo:/config-repo
        healthcheck:
            test: [ "CMD", "curl", "-fs", "http://localhost:8888/actuator/health" ]
            interval: 5s
            timeout: 2s
            retries: 60

    gateway:
        build: spring-cloud/gateway
        image: rufusy/ely-pos-gateway
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
            - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
            - EUREKA_SERVER_USR=${EUREKA_SERVER_USR}
            - EUREKA_SERVER_PWD=${EUREKA_SERVER_PWD}
        ports:
            - "8086:8080"
        depends_on:
            config-server:
                condition: service_healthy

    eureka:
        build: spring-cloud/eureka-server
        image: rufusy/ely-pos-eureka-server
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
            - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
            - EUREKA_SERVER_USR=${EUREKA_SERVER_USR}
            - EUREKA_SERVER_PWD=${EUREKA_SERVER_PWD}
        depends_on:
            config-server:
                condition: service_healthy

    inventory:
        build: microservices/inventory
        image: rufusy/ely-pos-inventory
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
            - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
            - EUREKA_SERVER_USR=${EUREKA_SERVER_USR}
            - EUREKA_SERVER_PWD=${EUREKA_SERVER_PWD}
        depends_on:
            postgres:
                condition: service_healthy
            config-server:
                condition: service_healthy