services:
  postgres:
    image: postgres:17
    container_name: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pos_dev
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pos_dev && echo 'Postgres is ready'" ]
      interval: 5s
      timeout: 2s
      retries: 60
