spring.application.name: gateway

server.port: 8086

server.error.include-message: always

app:
    eureka-server: localhost
    eureka-username: user
    eureka-password: pwd

eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
    client:
        service-url.defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5

logging:
    level:
        root: info
        com.elys.pos: debug
        org.springframework.cloud.gateway: trace
        org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring.cloud.gateway.routes:
    - id: inventory
      uri: lb://inventory
      predicates:
          - Path=/v1/inventory/{segment}
      filters:
          - SetPath=/v1/{segment}

    - id: eureka-api
      uri: http://${app.eureka-server}:8761
      predicates:
          - Path=/eureka/api/{segment}
      filters:
          - SetPath=/eureka/{segment}

    - id: eureka-web
      uri: http://${app.eureka-server}:8761
      predicates:
          - Path=/eureka/web
      filters:
          - SetPath=/

    - id: eureka-web-other
      uri: http://${app.eureka-server}:8761
      predicates:
          - Path=/eureka/**

---
spring.config.activate.on-profile: dev

server.port: 8080

app.eureka-server: eureka
